import Head from 'next/head'
import Image from 'next/image'
import AboutSection from '../components/ui/aboutSection/aboutSection'
import Hero from '../components/ui/hero/hero'
import MyWorkSection from '../components/ui/myWorkSection/myWorkSection'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero/>
      <AboutSection/>
      <MyWorkSection/>
    </div>
  )
}
